"""
Train supervised machine-learning models for historical forward drawdown risk.

Run after:
    python ml_dataset.py

This upgraded version adds the main improvements requested after the first ML run:

1. Top-decile risk analysis:
   Instead of only asking whether a model crosses a 0.50 probability threshold,
   we ask a more useful risk-monitoring question: what happened historically when
   a model placed an observation in its highest-risk 10% of scores?

2. Tuned thresholds:
   Rare-event problems should not blindly use 0.50 as the alert threshold. A 20%
   estimated crash-risk can be historically high when the base event rate is only
   5%-12%. We therefore tune each model's warning threshold on the validation
   period and apply that same threshold to the later test period.

3. Segment-specific models:
   A 30% drawdown means different things for SPY, NVDA, PLTR, and BTC. The code
   trains a global model and, where enough data exists, separate models for:
       - broad_index_etf
       - mega_cap_ai_tech
       - speculative_high_vol

4. Calibration tables:
   The code saves decile-based reliability tables so the dashboard can show
   whether high model scores historically corresponded to higher actual event
   rates. This does not make the model prophetic; it simply makes the probability
   scale more honest.

Outputs:
    models/*.pkl
    models/ml_preprocessor.pkl
    data/processed/ml_model_results.parquet
    data/processed/ml_test_predictions.parquet
    data/processed/ml_feature_importance.parquet
    data/processed/ml_thresholds.parquet
    data/processed/ml_top_decile_analysis.parquet
    data/processed/ml_calibration_table.parquet

Research framing:
    These models estimate whether current conditions resemble historical setups
    that were followed by a major forward drawdown. They do not predict exact
    tops, bottoms, or dates.
"""
from __future__ import annotations

import logging
import re
import sys
from pathlib import Path
from typing import Any

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    brier_score_loss,
    confusion_matrix,
    f1_score,
    matthews_corrcoef,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

try:
    from xgboost import XGBClassifier
except ImportError:  # pragma: no cover
    XGBClassifier = None

try:
    from imblearn.ensemble import BalancedRandomForestClassifier
except ImportError:  # pragma: no cover
    BalancedRandomForestClassifier = None

from config import BASE_DIR, LOG_DIR, PROCESSED_DIR

LOG_FILE = LOG_DIR / "model_training.log"
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(name)s | %(message)s",
    handlers=[logging.FileHandler(LOG_FILE, encoding="utf-8"), logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger("model_training")

MODELS_DIR = BASE_DIR / "models"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

TARGET = "burst_6m_segment"
DATASET_PATH = PROCESSED_DIR / "ml_burst_dataset.parquet"
RESULTS_PATH = PROCESSED_DIR / "ml_model_results.parquet"
PREDICTIONS_PATH = PROCESSED_DIR / "ml_test_predictions.parquet"
IMPORTANCE_PATH = PROCESSED_DIR / "ml_feature_importance.parquet"
THRESHOLDS_PATH = PROCESSED_DIR / "ml_thresholds.parquet"
TOP_DECILE_PATH = PROCESSED_DIR / "ml_top_decile_analysis.parquet"
CALIBRATION_PATH = PROCESSED_DIR / "ml_calibration_table.parquet"
PREPROCESSOR_PATH = MODELS_DIR / "ml_preprocessor.pkl"

# Extra rare-event outputs generated by rare_event_analysis.py. They are defined
# here for discoverability; the post-processing script writes them after model
# training completes.
RARE_EVENT_METRICS_PATH = PROCESSED_DIR / "ml_rare_event_metrics.parquet"
RISK_BUCKET_ANALYSIS_PATH = PROCESSED_DIR / "ml_risk_bucket_analysis.parquet"
TOP_K_LIFT_PATH = PROCESSED_DIR / "ml_top_k_lift_analysis.parquet"
CALIBRATED_PREDICTIONS_PATH = PROCESSED_DIR / "ml_calibrated_predictions.parquet"

# These segments intentionally overlap with the economic meaning of the project,
# not just yfinance asset classes. The goal is to avoid forcing SPY, Bitcoin, and
# Palantir to share one identical crash-risk anatomy.
SEGMENT_TICKERS: dict[str, set[str]] = {
    "broad_index_etf": {
        "SPY", "QQQ", "^GSPC", "^IXIC", "^DJI", "IWM", "XLK", "SOXX", "SMH", "XLF", "XHB", "EWJ", "FXI", "ASHR", "MCHI", "EWH", "XLE", "DBC", "GLD", "SLV", "USO", "IPO", "ARKK",
    },
    "mega_cap_ai_tech": {
        "NVDA", "MSFT", "AMD", "AVGO", "META", "GOOGL", "GOOG", "AMZN", "AAPL", "TSM", "ASML", "CSCO", "INTC", "ORCL", "QCOM", "IBM", "TXN", "MU", "LRCX", "KLAC", "ADBE", "CRM",
    },
    "speculative_high_vol": {
        "PLTR", "BTC-USD", "ETH-USD", "COIN", "TSLA", "GME", "AMC", "SPCE", "NKLA", "RIVN", "LCID", "ROKU", "ZM", "SHOP", "SNOW", "NET", "DDOG", "MDB", "CRWD", "U", "SQ", "XYZ",
    },
}

MIN_SEGMENT_ROWS = 800
MIN_SEGMENT_POSITIVES = 25

# Candidate features are intentionally listed by research meaning rather than
# blindly using every numeric column. This prevents leakage columns such as
# future_drawdown_burst_6m from slipping into the model.
CANDIDATE_FEATURES = [
    "price_log", "adjusted_close", "sma_50", "sma_200", "sma_50_over_200",
    "distance_from_200dma", "weekly_rsi", "daily_rsi", "drawdown_pct",
    "volatility_30d", "return_21d", "return_63d", "return_126d",
    "return_252d", "zscore_price", "parabolic_acceleration",
    "parabolic_acceleration_proxy", "warning_score", "recovery_score",
    "price_to_sales", "pe_ratio", "ev_to_sales", "revenue_ttm",
    "net_income_ttm", "market_cap", "enterprise_value", "valuation_warning_score",
    "ps_to_historical_median", "pe_to_historical_median",
    "ev_sales_to_historical_median", "revenue_ttm_yoy_pct", "net_income_ttm_yoy_pct",
    "federal_funds_rate", "federal_funds_change_3p", "federal_funds_change_12p",
    "ten_year_treasury_yield", "ten_year_treasury_change_3p",
    "ten_year_treasury_change_12p", "yield_curve_spread", "yield_curve_change_3p",
    "yield_curve_change_12p", "cpi_yoy", "unemployment_rate",
    "unemployment_change_3p", "unemployment_change_12p", "recession_indicator",
    "financial_stress_index", "mortgage_rate", "mortgage_rate_change_12p",
    "case_shiller_yoy", "gdp_yoy_proxy", "wilshire_5000_yoy",
]


def debug_print(message: str) -> None:
    print(f"[MODEL_TRAINING DEBUG] {message}")
    logger.info(message)


def slugify(value: str) -> str:
    """Make a safe filename slug from a model or segment name."""
    return re.sub(r"[^a-z0-9]+", "_", value.lower()).strip("_")


def infer_asset_segment(ticker: str) -> str:
    """Assign each ticker to the most relevant ML segment.

    The ordering matters. Some ETFs such as ARKK are broad baskets but behave
    like high-volatility growth assets; however, for this first version we place
    ETFs in broad_index_etf so the segment remains stable. Individual speculative
    names and crypto go to speculative_high_vol. Mega-cap AI and legacy tech go
    to mega_cap_ai_tech.
    """
    for segment, tickers in SEGMENT_TICKERS.items():
        if ticker in tickers:
            return segment
    if ticker.endswith("-USD"):
        return "speculative_high_vol"
    if ticker.startswith("^"):
        return "broad_index_etf"
    return "other_single_name"


def load_dataset() -> pd.DataFrame:
    if not DATASET_PATH.exists():
        raise FileNotFoundError(f"Missing {DATASET_PATH}. Run python ml_dataset.py first.")
    df = pd.read_parquet(DATASET_PATH)
    if df.empty:
        raise ValueError(f"{DATASET_PATH} is empty. Re-run python ml_dataset.py and inspect logs.")
    df["date"] = pd.to_datetime(df["date"])
    df["asset_segment"] = df["ticker"].astype(str).map(infer_asset_segment)
    debug_print(f"Loaded ML dataset: shape={df.shape}")
    debug_print("Rows by segment:\n" + df["asset_segment"].value_counts().to_string())
    return df.sort_values(["date", "ticker"]).reset_index(drop=True)


def select_feature_columns(df: pd.DataFrame) -> list[str]:
    available = []
    for col in CANDIDATE_FEATURES:
        if col in df.columns and pd.api.types.is_numeric_dtype(df[col]):
            available.append(col)

    leakage_markers = ["future_", "target_valid_", "burst_3m", "burst_6m", "burst_12m"]
    clean = [c for c in available if not any(marker in c for marker in leakage_markers)]
    if not clean:
        raise ValueError("No usable numeric ML features were found. Inspect ml_burst_dataset.parquet columns.")
    debug_print(f"Selected {len(clean)} ML features:\n" + "\n".join(f"  - {c}" for c in clean))
    return clean


def clean_feature_matrix(X: pd.DataFrame, feature_cols: list[str], context: str = "feature_matrix") -> pd.DataFrame:
    """Return a finite numeric feature matrix for scikit-learn.

    Why this matters:
    -----------------
    Some financial ratios naturally explode when the denominator is zero or
    close to zero. Examples include price-to-sales when revenue is missing,
    EV/sales when sales are near zero, and growth ratios around sign changes.
    Pandas can store those values as +inf or -inf. Humans understand that as
    "not usable / undefined," but scikit-learn's imputers and models refuse to
    train when any feature contains infinity.

    The correct treatment is not to pretend infinity is a real economic value.
    We convert +/-inf and absurdly huge numeric artifacts to NaN, then the
    existing SimpleImputer inside each model pipeline replaces NaN with the
    training-set median. This preserves the no-look-ahead design because medians
    are learned only from the training data during each fit.
    """
    clean = X.copy()

    for col in feature_cols:
        if col not in clean.columns:
            clean[col] = np.nan

        clean[col] = pd.to_numeric(clean[col], errors="coerce")

    clean = clean[feature_cols]

    values = clean.to_numpy(dtype=float, copy=True)
    non_finite_mask = ~np.isfinite(values)
    non_finite_count = int(non_finite_mask.sum())

    # Values beyond this range are usually division artifacts rather than
    # meaningful market information. We set them to NaN so the model's imputer
    # handles them consistently. This threshold is intentionally huge so real
    # market caps in the trillions are not affected.
    too_large_mask = np.abs(values) > 1e100
    too_large_count = int(too_large_mask.sum())

    if non_finite_count or too_large_count:
        bad_mask = non_finite_mask | too_large_mask
        bad_by_col = pd.Series(bad_mask.sum(axis=0), index=feature_cols)
        bad_by_col = bad_by_col[bad_by_col > 0].sort_values(ascending=False).head(20)
        debug_print(
            f"{context}: replacing {non_finite_count:,} non-finite values and "
            f"{too_large_count:,} extreme values with NaN before modeling. "
            f"Top affected columns:\n{bad_by_col.to_string()}"
        )
        values[bad_mask] = np.nan

    return pd.DataFrame(values, columns=feature_cols, index=X.index)


def clean_model_dataset(df: pd.DataFrame, feature_cols: list[str], context: str = "dataset") -> pd.DataFrame:
    """Clean the feature columns inside a full labeled dataset.

    This helper keeps metadata columns such as date, ticker, and target intact,
    but replaces infinite feature values with NaN. It prevents both the
    train/evaluate pass and the final refit pass from failing on ratio columns
    that have mathematically undefined values.
    """
    out = df.copy()
    out.loc[:, feature_cols] = clean_feature_matrix(out[feature_cols], feature_cols, context=context)
    return out


def build_chronological_splits(df: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """Create train/validation/test splits by date, never random shuffling."""
    unique_dates = np.array(sorted(df["date"].dropna().unique()))
    if len(unique_dates) < 30:
        raise ValueError("Not enough unique weekly dates for chronological ML validation.")

    train_cut = unique_dates[int(len(unique_dates) * 0.70)]
    val_cut = unique_dates[int(len(unique_dates) * 0.85)]

    train = df[df["date"] <= train_cut].copy()
    val = df[(df["date"] > train_cut) & (df["date"] <= val_cut)].copy()
    test = df[df["date"] > val_cut].copy()

    debug_print(
        f"Chronological split dates: train<= {pd.Timestamp(train_cut).date()}, "
        f"val<= {pd.Timestamp(val_cut).date()}, test after val_cut"
    )
    for name, part in [("train", train), ("validation", val), ("test", test)]:
        counts = part[TARGET].value_counts().sort_index()
        debug_print(f"{name} size={len(part):,}; class balance:\n{counts.to_string() if not counts.empty else 'empty'}")

    if train[TARGET].nunique() < 2:
        raise ValueError("Training split has only one target class. Widen ticker/date universe or adjust target threshold.")
    if val.empty or test.empty:
        raise ValueError("Validation or test split is empty. Need more dated rows.")
    return train, val, test


def make_logistic_pipeline(feature_cols: list[str]) -> Pipeline:
    """Create an interpretable GLM-style baseline.

    Logistic regression gets scaled inputs so coefficients are comparable. Median
    imputation is used because real market/fundamental data has holes.
    """
    preprocessor = ColumnTransformer(
        transformers=[(
            "numeric",
            Pipeline(steps=[("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())]),
            feature_cols,
        )],
        remainder="drop",
        verbose_feature_names_out=False,
    )
    model = LogisticRegression(max_iter=3000, class_weight="balanced", solver="lbfgs")
    return Pipeline(steps=[("preprocessor", preprocessor), ("model", model)])


def make_elastic_net_logistic_pipeline(feature_cols: list[str]) -> Pipeline:
    """Create an Elastic Net logistic baseline.

    This sits between pure ridge-like shrinkage and lasso-like sparsity. In a
    noisy rare-event feature set, it can zero out weak coefficients while still
    stabilizing correlated technical/macro variables.
    """
    preprocessor = ColumnTransformer(
        transformers=[(
            "numeric",
            Pipeline(steps=[("imputer", SimpleImputer(strategy="median")), ("scaler", StandardScaler())]),
            feature_cols,
        )],
        remainder="drop",
        verbose_feature_names_out=False,
    )
    model = LogisticRegression(
        max_iter=5000,
        class_weight="balanced",
        solver="saga",
        penalty="elasticnet",
        l1_ratio=0.50,
    )
    return Pipeline(steps=[("preprocessor", preprocessor), ("model", model)])


def make_random_forest_pipeline(feature_cols: list[str]) -> Pipeline:
    preprocessor = ColumnTransformer(
        transformers=[("numeric", SimpleImputer(strategy="median"), feature_cols)],
        remainder="drop",
        verbose_feature_names_out=False,
    )
    model = RandomForestClassifier(
        n_estimators=500,
        max_depth=8,
        min_samples_leaf=8,
        random_state=42,
        n_jobs=-1,
        class_weight="balanced_subsample",
    )
    return Pipeline(steps=[("preprocessor", preprocessor), ("model", model)])


def make_balanced_random_forest_pipeline(feature_cols: list[str]) -> Pipeline | None:
    """Create a Balanced Random Forest benchmark for imbalanced crash-risk labels.

    Standard random forests can still be dominated by the majority class even
    when class weights are used. BalancedRandomForestClassifier draws balanced
    bootstrap samples for each tree, so every tree is forced to learn from the
    minority crash/drawdown class. This does not invent synthetic market rows.
    It is therefore safer for financial time-series data than SMOTE as a first
    imbalance-specific tree benchmark.
    """
    if BalancedRandomForestClassifier is None:
        debug_print("imbalanced-learn is not installed. Balanced Random Forest will be skipped.")
        return None
    preprocessor = ColumnTransformer(
        transformers=[("numeric", SimpleImputer(strategy="median"), feature_cols)],
        remainder="drop",
        verbose_feature_names_out=False,
    )
    model = BalancedRandomForestClassifier(
        n_estimators=500,
        max_depth=8,
        min_samples_leaf=8,
        random_state=42,
        n_jobs=-1,
        replacement=True,
        sampling_strategy="all",
    )
    return Pipeline(steps=[("preprocessor", preprocessor), ("model", model)])


def make_xgboost_pipeline(feature_cols: list[str], y_train: pd.Series) -> Pipeline | None:
    if XGBClassifier is None:
        debug_print("xgboost is not installed. XGBoost model will be skipped.")
        return None
    positives = int((y_train == 1).sum())
    negatives = int((y_train == 0).sum())
    scale_pos_weight = (negatives / positives) if positives > 0 else 1.0
    preprocessor = ColumnTransformer(
        transformers=[("numeric", SimpleImputer(strategy="median"), feature_cols)],
        remainder="drop",
        verbose_feature_names_out=False,
    )
    model = XGBClassifier(
        n_estimators=450,
        max_depth=3,
        learning_rate=0.035,
        subsample=0.85,
        colsample_bytree=0.85,
        min_child_weight=5,
        reg_lambda=2.0,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=42,
        n_jobs=-1,
        scale_pos_weight=scale_pos_weight,
    )
    return Pipeline(steps=[("preprocessor", preprocessor), ("model", model)])


def safe_metric(metric_name: str, y_true: np.ndarray, y_prob: np.ndarray, y_pred: np.ndarray) -> float:
    try:
        if metric_name == "roc_auc":
            return float(roc_auc_score(y_true, y_prob)) if len(np.unique(y_true)) >= 2 else np.nan
        if metric_name == "pr_auc":
            return float(average_precision_score(y_true, y_prob)) if len(np.unique(y_true)) >= 2 else np.nan
        if metric_name == "accuracy":
            return float(accuracy_score(y_true, y_pred))
        if metric_name == "precision":
            return float(precision_score(y_true, y_pred, zero_division=0))
        if metric_name == "recall":
            return float(recall_score(y_true, y_pred, zero_division=0))
        if metric_name == "f1":
            return float(f1_score(y_true, y_pred, zero_division=0))
        if metric_name == "mcc":
            return float(matthews_corrcoef(y_true, y_pred)) if len(np.unique(y_true)) >= 2 and len(np.unique(y_pred)) >= 2 else 0.0
        if metric_name == "brier_score":
            return float(brier_score_loss(y_true, np.clip(y_prob, 0, 1)))
    except Exception as exc:  # pragma: no cover
        debug_print(f"Metric {metric_name} failed: {exc}")
    return np.nan


def predict_probability(model: Pipeline, X: pd.DataFrame) -> np.ndarray:
    if hasattr(model, "predict_proba"):
        return model.predict_proba(X)[:, 1]
    raw = model.decision_function(X)
    return 1.0 / (1.0 + np.exp(-raw))


def build_rule_based_probabilities(df: pd.DataFrame) -> np.ndarray:
    if "warning_score" not in df.columns:
        return np.full(len(df), 0.0)
    return (pd.to_numeric(df["warning_score"], errors="coerce").fillna(0.0).clip(0, 100) / 100.0).to_numpy()


def minimum_precision_requirement(base_rate: float) -> float:
    """Set a precision floor so tuned thresholds cannot win by flagging everything.

    In rare-event work, maximizing F1 alone can choose absurdly low thresholds.
    A model can get high recall by predicting nearly every row as risky, but that
    creates a useless warning system. This function requires precision to beat
    the base event rate by a meaningful margin while still allowing broad-index
    events to remain detectable.
    """
    if not np.isfinite(base_rate):
        return 0.10
    return float(min(0.45, max(0.05, base_rate * 1.50)))


def choose_threshold_on_validation(y_true: np.ndarray, y_prob: np.ndarray) -> dict[str, float | str]:
    """Select an alert threshold with rare-event safeguards.

    The old version maximized validation F1, which improved recall but sometimes
    chose thresholds so low that nearly every row became an alert. This stricter
    version does three things:

    1. requires precision to exceed a minimum floor based on the validation base rate;
    2. limits the alert rate so a model cannot declare almost everything risky;
    3. falls back to a high-percentile threshold if no candidate satisfies both constraints.
    """
    y_true = np.asarray(y_true).astype(int)
    y_prob = np.asarray(y_prob, dtype=float)
    finite = np.isfinite(y_prob)
    y_true = y_true[finite]
    y_prob = y_prob[finite]
    if len(y_true) == 0:
        return {"threshold_value": 0.50, "threshold_strategy": "fallback_0_50_empty_validation", "validation_f1_at_threshold": np.nan}

    base_rate = float(np.mean(y_true))
    min_precision = minimum_precision_requirement(base_rate)
    max_alert_rate = 0.35 if base_rate < 0.20 else 0.60

    candidates = set(np.linspace(0.005, 0.995, 199).round(4))
    for q in [50, 60, 70, 75, 80, 85, 90, 92.5, 95, 97.5, 99]:
        candidates.add(round(float(np.nanpercentile(y_prob, q)), 4))
    candidates = sorted(c for c in candidates if 0.0 <= c <= 1.0)

    best = None
    fallback = None
    for threshold in candidates:
        pred = (y_prob >= threshold).astype(int)
        alert_rate = float(pred.mean()) if len(pred) else 0.0
        precision = precision_score(y_true, pred, zero_division=0)
        recall = recall_score(y_true, pred, zero_division=0)
        f1 = f1_score(y_true, pred, zero_division=0)
        score = f1
        row = {
            "threshold_value": float(threshold),
            "threshold_strategy": "validation_max_f1_with_min_precision_constraint",
            "validation_f1_at_threshold": float(f1),
            "validation_precision_at_threshold": float(precision),
            "validation_recall_at_threshold": float(recall),
            "validation_alert_rate_at_threshold": float(alert_rate),
            "validation_base_event_rate": float(base_rate),
            "minimum_precision_required": float(min_precision),
            "maximum_alert_rate_allowed": float(max_alert_rate),
        }
        if fallback is None or (alert_rate <= max_alert_rate and f1 > fallback[0]):
            fallback = (f1, row)
        if precision >= min_precision and alert_rate <= max_alert_rate:
            if best is None or score > best[0] or (np.isclose(score, best[0]) and precision > best[1]["validation_precision_at_threshold"]):
                best = (score, row)

    if best is not None:
        return best[1]

    # If no threshold satisfies the precision constraint, use a conservative high
    # percentile rather than a threshold that flags the whole dataset.
    conservative = float(np.nanpercentile(y_prob, 90)) if len(y_prob) else 0.50
    if fallback is not None:
        row = fallback[1]
        row["threshold_value"] = max(row["threshold_value"], conservative)
        row["threshold_strategy"] = "fallback_conservative_when_precision_constraint_unmet"
        return row
    return {"threshold_value": conservative, "threshold_strategy": "fallback_90th_percentile", "validation_f1_at_threshold": np.nan}

def evaluate_predictions(model_name: str, segment: str, split_name: str, y_true: np.ndarray, y_prob: np.ndarray, threshold: float) -> dict[str, Any]:
    """Compute rare-event metrics including false-positive burden and MCC.

    Accuracy is intentionally de-emphasized because a model can look accurate by
    predicting the majority non-event class. MCC and false positives per true
    positive make the alert-quality problem harder to hide.
    """
    y_pred = (y_prob >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    positive_rate = float(np.mean(y_true)) if len(y_true) else np.nan
    alert_rate = float(np.mean(y_pred)) if len(y_pred) else np.nan
    precision = safe_metric("precision", y_true, y_prob, y_pred)
    recall = safe_metric("recall", y_true, y_prob, y_pred)
    out = {
        "model": model_name,
        "asset_segment": segment,
        "model_scope": segment,
        "split": split_name,
        "threshold_value": float(threshold),
        "n_rows": int(len(y_true)),
        "positive_rate": positive_rate,
        "alert_rate": alert_rate,
        "roc_auc": safe_metric("roc_auc", y_true, y_prob, y_pred),
        "pr_auc": safe_metric("pr_auc", y_true, y_prob, y_pred),
        "accuracy": safe_metric("accuracy", y_true, y_prob, y_pred),
        "precision": precision,
        "recall": recall,
        "f1": safe_metric("f1", y_true, y_prob, y_pred),
        "mcc": safe_metric("mcc", y_true, y_prob, y_pred),
        "brier_score": safe_metric("brier_score", y_true, y_prob, y_pred),
        "true_negative": int(tn),
        "false_positive": int(fp),
        "false_negative": int(fn),
        "true_positive": int(tp),
        "false_positives_per_true_positive": float(fp / tp) if tp > 0 else np.inf,
        "false_negatives_per_true_positive": float(fn / tp) if tp > 0 else np.inf,
        "miss_rate": float(fn / (fn + tp)) if (fn + tp) > 0 else np.nan,
        "specificity": float(tn / (tn + fp)) if (tn + fp) > 0 else np.nan,
        "precision_lift_vs_base_rate": float(precision / positive_rate) if positive_rate and np.isfinite(precision) else np.nan,
    }
    debug_print(f"{model_name} / {segment} / {split_name} metrics: {out}")
    return out

def add_prediction_rows(split_df: pd.DataFrame, model_name: str, segment: str, split_name: str, y_prob: np.ndarray, threshold: float) -> pd.DataFrame:
    cols = ["date", "ticker", "asset_segment", TARGET, "warning_score"]
    cols = [c for c in cols if c in split_df.columns]
    out = split_df[cols].copy()
    out["model"] = model_name
    out["model_scope"] = segment
    out["split"] = split_name
    out["probability"] = y_prob
    out["threshold_value"] = float(threshold)
    out["prediction"] = (out["probability"] >= threshold).astype(int)
    out["risk_rank_pct"] = out["probability"].rank(pct=True, method="average")
    out["top_decile_flag"] = out["risk_rank_pct"] >= 0.90
    out["top_5pct_flag"] = out["risk_rank_pct"] >= 0.95
    out["risk_bucket"] = pd.cut(
        out["risk_rank_pct"],
        bins=[-np.inf, 0.50, 0.75, 0.90, 0.95, np.inf],
        labels=["Bottom 50%", "50-75%", "75-90%", "90-95%", "Top 5%"],
    ).astype(str)
    return out


def top_decile_analysis(pred_df: pd.DataFrame) -> dict[str, Any]:
    if pred_df.empty:
        return {}
    y = pred_df[TARGET].astype(int)
    top = pred_df[pred_df["top_decile_flag"]].copy()
    base_rate = float(y.mean()) if len(y) else np.nan
    top_rate = float(top[TARGET].astype(int).mean()) if len(top) else np.nan
    return {
        "model": pred_df["model"].iloc[0],
        "model_scope": pred_df["model_scope"].iloc[0],
        "split": pred_df["split"].iloc[0],
        "n_rows": int(len(pred_df)),
        "top_decile_rows": int(len(top)),
        "base_event_rate": base_rate,
        "top_decile_event_rate": top_rate,
        "lift_vs_base_rate": float(top_rate / base_rate) if base_rate and np.isfinite(base_rate) and np.isfinite(top_rate) else np.nan,
        "top_decile_true_positives": int(top[TARGET].sum()) if len(top) else 0,
        "mean_probability_top_decile": float(top["probability"].mean()) if len(top) else np.nan,
        "min_probability_top_decile": float(top["probability"].min()) if len(top) else np.nan,
    }


def calibration_table_from_predictions(pred_df: pd.DataFrame, n_bins: int = 10) -> pd.DataFrame:
    """Create decile reliability table for a prediction set.

    If a model is calibrated, rows with predicted risk around 20% should have an
    empirical event rate close to 20%. Financial crash models are rarely perfect,
    so this table is meant to reveal whether the probability scale is honest.
    """
    if pred_df.empty or pred_df["probability"].nunique(dropna=True) < 2:
        return pd.DataFrame()
    tmp = pred_df.copy()
    try:
        tmp["probability_bin"] = pd.qcut(tmp["probability"], q=min(n_bins, tmp["probability"].nunique()), duplicates="drop")
    except ValueError:
        return pd.DataFrame()
    rows = []
    for bin_value, g in tmp.groupby("probability_bin", observed=True):
        rows.append({
            "model": g["model"].iloc[0],
            "model_scope": g["model_scope"].iloc[0],
            "split": g["split"].iloc[0],
            "probability_bin": str(bin_value),
            "bin_left": float(bin_value.left),
            "bin_right": float(bin_value.right),
            "n_rows": int(len(g)),
            "mean_predicted_probability": float(g["probability"].mean()),
            "empirical_event_rate": float(g[TARGET].astype(int).mean()),
        })
    return pd.DataFrame(rows)


def extract_feature_importance(model_name: str, segment: str, pipeline: Pipeline, feature_cols: list[str]) -> pd.DataFrame:
    estimator = pipeline.named_steps.get("model")
    rows: list[dict[str, Any]] = []
    if hasattr(estimator, "coef_"):
        for feature, value in zip(feature_cols, estimator.coef_[0]):
            rows.append({"model": model_name, "model_scope": segment, "feature": feature, "importance": float(abs(value)), "signed_value": float(value)})
    elif hasattr(estimator, "feature_importances_"):
        for feature, value in zip(feature_cols, estimator.feature_importances_):
            rows.append({"model": model_name, "model_scope": segment, "feature": feature, "importance": float(value), "signed_value": np.nan})
    out = pd.DataFrame(rows)
    if out.empty:
        return pd.DataFrame(columns=["model", "model_scope", "feature", "importance", "signed_value"])
    return out.sort_values(["model_scope", "model", "importance"], ascending=[True, True, False]).reset_index(drop=True)


def make_model_set(feature_cols: list[str], y_train: pd.Series) -> dict[str, Pipeline]:
    models: dict[str, Pipeline] = {
        "Logistic Regression": make_logistic_pipeline(feature_cols),
        "Elastic Net Logistic": make_elastic_net_logistic_pipeline(feature_cols),
        "Random Forest": make_random_forest_pipeline(feature_cols),
    }
    balanced_rf = make_balanced_random_forest_pipeline(feature_cols)
    if balanced_rf is not None:
        models["Balanced Random Forest"] = balanced_rf
    xgb = make_xgboost_pipeline(feature_cols, y_train)
    if xgb is not None:
        models["XGBoost"] = xgb
    return models


def train_evaluate_scope(scope_name: str, scope_df: pd.DataFrame, feature_cols: list[str]) -> tuple[list[dict[str, Any]], list[pd.DataFrame], list[pd.DataFrame], list[dict[str, Any]], list[pd.DataFrame], dict[str, float]]:
    """Train/evaluate models for one scope: global or one segment."""
    debug_print(f"Training scope={scope_name}; rows={len(scope_df):,}")
    train, val, test = build_chronological_splits(scope_df)
    X_train = clean_feature_matrix(train[feature_cols], feature_cols, context=f"{scope_name} train")
    y_train = train[TARGET].astype(int)
    models = make_model_set(feature_cols, y_train)

    results: list[dict[str, Any]] = []
    predictions: list[pd.DataFrame] = []
    calibration_frames: list[pd.DataFrame] = []
    top_decile_rows: list[dict[str, Any]] = []
    threshold_rows: list[dict[str, Any]] = []

    # Rule-based baseline: tune its warning_score threshold on validation, then
    # carry that same threshold to test. This is more honest than using 0.50 just
    # because it is visually familiar.
    rule_val_prob = build_rule_based_probabilities(val)
    rule_threshold = choose_threshold_on_validation(val[TARGET].astype(int).to_numpy(), rule_val_prob)
    threshold_rows.append({"model": "Rule-Based Warning Score", "model_scope": scope_name, **rule_threshold})
    for split_name, split_df in [("validation", val), ("test", test)]:
        y_true = split_df[TARGET].astype(int).to_numpy()
        y_prob = build_rule_based_probabilities(split_df)
        threshold = float(rule_threshold["threshold_value"])
        results.append(evaluate_predictions("Rule-Based Warning Score", scope_name, split_name, y_true, y_prob, threshold))
        pred_df = add_prediction_rows(split_df, "Rule-Based Warning Score", scope_name, split_name, y_prob, threshold)
        predictions.append(pred_df)
        top_decile_rows.append(top_decile_analysis(pred_df))
        cal = calibration_table_from_predictions(pred_df)
        if not cal.empty:
            calibration_frames.append(cal)

    # ML models: fit on train only, tune threshold on validation, evaluate on test.
    for model_name, model in models.items():
        debug_print(f"Training model={model_name}; scope={scope_name}")
        model.fit(X_train, y_train)
        X_val = clean_feature_matrix(val[feature_cols], feature_cols, context=f"{scope_name} validation {model_name}")
        val_prob = predict_probability(model, X_val)
        threshold_info = choose_threshold_on_validation(val[TARGET].astype(int).to_numpy(), val_prob)
        threshold_rows.append({"model": model_name, "model_scope": scope_name, **threshold_info})
        threshold = float(threshold_info["threshold_value"])
        for split_name, split_df in [("validation", val), ("test", test)]:
            y_true = split_df[TARGET].astype(int).to_numpy()
            X_split = clean_feature_matrix(split_df[feature_cols], feature_cols, context=f"{scope_name} {split_name} {model_name}")
            y_prob = predict_probability(model, X_split)
            results.append(evaluate_predictions(model_name, scope_name, split_name, y_true, y_prob, threshold))
            pred_df = add_prediction_rows(split_df, model_name, scope_name, split_name, y_prob, threshold)
            predictions.append(pred_df)
            top_decile_rows.append(top_decile_analysis(pred_df))
            cal = calibration_table_from_predictions(pred_df)
            if not cal.empty:
                calibration_frames.append(cal)

    return results, predictions, calibration_frames, top_decile_rows, [pd.DataFrame(threshold_rows)], {}


def refit_final_models_by_scope(labeled: pd.DataFrame, feature_cols: list[str]) -> tuple[dict[str, dict[str, Pipeline]], pd.DataFrame, pd.DataFrame]:
    """Refit final inference models on all completed labels for each usable scope."""
    final_models: dict[str, dict[str, Pipeline]] = {}
    importance_frames: list[pd.DataFrame] = []
    final_calibration_frames: list[pd.DataFrame] = []

    scope_frames = {"global": labeled}
    for segment in ["broad_index_etf", "mega_cap_ai_tech", "speculative_high_vol"]:
        segment_df = labeled[labeled["asset_segment"].eq(segment)].copy()
        if len(segment_df) >= MIN_SEGMENT_ROWS and segment_df[TARGET].sum() >= MIN_SEGMENT_POSITIVES and segment_df[TARGET].nunique() == 2:
            scope_frames[segment] = segment_df
        else:
            debug_print(f"Skipping final segment model {segment}: rows={len(segment_df):,}, positives={int(segment_df[TARGET].sum()) if not segment_df.empty else 0}")

    for scope_name, scope_df in scope_frames.items():
        X_all = clean_feature_matrix(scope_df[feature_cols], feature_cols, context=f"{scope_name} final_refit")
        y_all = scope_df[TARGET].astype(int)
        models = make_model_set(feature_cols, y_all)
        final_models[scope_name] = {}
        for model_name, model in models.items():
            debug_print(f"Refitting final model={model_name}; scope={scope_name}; rows={len(scope_df):,}")
            model.fit(X_all, y_all)
            final_models[scope_name][model_name] = model

            scope_slug = slugify(scope_name)
            model_slug = slugify(model_name)
            path = MODELS_DIR / f"{scope_slug}_{model_slug}_burst_6m.pkl"
            joblib.dump(model, path)

            # Keep legacy global filenames so older instructions still work.
            if scope_name == "global":
                legacy = {
                    "Logistic Regression": "logistic_regression_burst_6m.pkl",
                    "Elastic Net Logistic": "elastic_net_logistic_burst_6m.pkl",
                    "Random Forest": "random_forest_burst_6m.pkl",
                    "Balanced Random Forest": "balanced_random_forest_burst_6m.pkl",
                    "XGBoost": "xgboost_burst_6m.pkl",
                }.get(model_name)
                if legacy:
                    joblib.dump(model, MODELS_DIR / legacy)

            importance_frames.append(extract_feature_importance(model_name, scope_name, model, feature_cols))
            probs = predict_probability(model, X_all)
            pred_df = add_prediction_rows(scope_df, model_name, scope_name, "historical_in_sample_final", probs, threshold=0.50)
            cal = calibration_table_from_predictions(pred_df)
            if not cal.empty:
                final_calibration_frames.append(cal)

    importance_df = pd.concat([f for f in importance_frames if not f.empty], ignore_index=True) if importance_frames else pd.DataFrame()
    final_calibration_df = pd.concat([f for f in final_calibration_frames if not f.empty], ignore_index=True) if final_calibration_frames else pd.DataFrame()
    return final_models, importance_df, final_calibration_df


def main() -> None:
    debug_print("Model training start")
    df = load_dataset()
    if TARGET not in df.columns or f"target_valid_{TARGET}" not in df.columns:
        raise ValueError(f"Dataset must contain {TARGET} and target_valid_{TARGET}. Re-run python ml_dataset.py.")

    labeled = df[(df[f"target_valid_{TARGET}"] == True) & df[TARGET].notna()].copy()
    labeled[TARGET] = labeled[TARGET].astype(int)
    debug_print(f"Completed labeled rows for {TARGET}: {len(labeled):,}")
    debug_print(f"Overall class balance:\n{labeled[TARGET].value_counts().sort_index().to_string()}")

    feature_cols = select_feature_columns(labeled)
    labeled = clean_model_dataset(labeled, feature_cols, context="completed labeled ML dataset")

    scope_dfs = {"global": labeled}
    for segment in ["broad_index_etf", "mega_cap_ai_tech", "speculative_high_vol"]:
        segment_df = labeled[labeled["asset_segment"].eq(segment)].copy()
        if len(segment_df) >= MIN_SEGMENT_ROWS and segment_df[TARGET].sum() >= MIN_SEGMENT_POSITIVES and segment_df[TARGET].nunique() == 2:
            scope_dfs[segment] = segment_df
        else:
            debug_print(f"Skipping evaluation segment {segment}: rows={len(segment_df):,}, positives={int(segment_df[TARGET].sum()) if not segment_df.empty else 0}")

    all_results: list[dict[str, Any]] = []
    all_predictions: list[pd.DataFrame] = []
    all_calibration: list[pd.DataFrame] = []
    all_top_decile: list[dict[str, Any]] = []
    threshold_frames: list[pd.DataFrame] = []

    for scope_name, scope_df in scope_dfs.items():
        try:
            results, predictions, calibration_frames, top_rows, threshold_df_list, _ = train_evaluate_scope(scope_name, scope_df, feature_cols)
            all_results.extend(results)
            all_predictions.extend(predictions)
            all_calibration.extend(calibration_frames)
            all_top_decile.extend([r for r in top_rows if r])
            threshold_frames.extend(threshold_df_list)
        except Exception as exc:  # noqa: BLE001
            debug_print(f"Skipping scope={scope_name} after training/evaluation error: {exc}")

    results_df = pd.DataFrame(all_results)
    predictions_df = pd.concat(all_predictions, ignore_index=True) if all_predictions else pd.DataFrame()
    thresholds_df = pd.concat(threshold_frames, ignore_index=True) if threshold_frames else pd.DataFrame()
    top_decile_df = pd.DataFrame(all_top_decile)
    calibration_df = pd.concat(all_calibration, ignore_index=True) if all_calibration else pd.DataFrame()

    final_models, importance_df, final_calibration_df = refit_final_models_by_scope(labeled, feature_cols)
    if not final_calibration_df.empty:
        calibration_df = pd.concat([calibration_df, final_calibration_df], ignore_index=True) if not calibration_df.empty else final_calibration_df

    bundle = {
        "target": TARGET,
        "feature_columns": feature_cols,
        "model_scopes": sorted(final_models.keys()),
        "segment_tickers": {k: sorted(v) for k, v in SEGMENT_TICKERS.items()},
        "available_models_by_scope": {scope: sorted(models.keys()) for scope, models in final_models.items()},
        "threshold_table_path": str(THRESHOLDS_PATH),
        "calibration_table_path": str(CALIBRATION_PATH),
        "training_min_date": str(labeled["date"].min().date()),
        "training_max_date": str(labeled["date"].max().date()),
        "notes": (
            "Models estimate segment-adjusted historical forward drawdown risk. Tuned thresholds are constrained by minimum precision and alert-rate guards, not arbitrary 0.50. "
            "Segment models are used when enough history exists; otherwise inference falls back to the global model."
        ),
    }
    joblib.dump(bundle, PREPROCESSOR_PATH)

    RESULTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    results_df.to_parquet(RESULTS_PATH, index=False)
    predictions_df.to_parquet(PREDICTIONS_PATH, index=False)
    importance_df.to_parquet(IMPORTANCE_PATH, index=False)
    thresholds_df.to_parquet(THRESHOLDS_PATH, index=False)
    top_decile_df.to_parquet(TOP_DECILE_PATH, index=False)
    calibration_df.to_parquet(CALIBRATION_PATH, index=False)

    debug_print(f"Saved model results: {RESULTS_PATH}")
    debug_print(f"Saved predictions: {PREDICTIONS_PATH}")
    debug_print(f"Saved feature importances: {IMPORTANCE_PATH}")
    debug_print(f"Saved tuned thresholds: {THRESHOLDS_PATH}")
    debug_print(f"Saved top-decile analysis: {TOP_DECILE_PATH}")
    debug_print(f"Saved calibration tables: {CALIBRATION_PATH}")
    debug_print("Model training complete")


if __name__ == "__main__":
    main()
